### Exercise 1

In [2]:
fullname = 'Bob Jones'
start_idx = 0
space_idx = fullname.find(' ')
last_name = fullname[space_idx+1 : len(fullname)]
last_name

'Jones'

### Execise 2

In [3]:
text = 'A lazy dog jumped over a log.'
positions = []
for i in range(len(text)-1):
    if(text[i:i+2] == 'og'):
        positions.append(i)
positions

[8, 26]

In [4]:
sentence = 'She sells seashells by the sea shore.'
positions = []
for i in range(len(sentence)):
    if(sentence[i : i+len('sea')] == 'sea'):
        positions.append(i)

positions

[10, 27]

### Exercise 3

In [5]:
text = 'A lazy dog jumped over a log.'
newText = text.replace('dog', 'cat')
newText

'A lazy cat jumped over a log.'

In [6]:
text = 'A lazy dog jumped over a log.'
newText = text.replace('lazy ', '')
newText

'A dog jumped over a log.'

### Exercise 4

In [7]:
word = 'A lazy dog jumped over a log.'
sentence_arr = word.split(' ')

for counter in sentence_arr:
    print(counter)

A
lazy
dog
jumped
over
a
log.

In [8]:
joint_sentence = ' '.join(sentence_arr)
joint_sentence

'A lazy dog jumped over a log.'

In [9]:
sentence_array = ['A', 'lazy', 'dog', 'jumped', 'over', 'a', 'log.']
joint_sentence = ','.join(sentence_array)
joint_sentence

'A,lazy,dog,jumped,over,a,log.'

## DataFrame

### Exercise 5

In [10]:
import pandas as pd

dataset = {'First Name': ['John', 'Holly', 'Nina'],
           'Grade': [85, 90, 95]}

df = pd.DataFrame(dataset)
df

  First Name  Grade
0       John     85
1      Holly     90
2       Nina     95

In [11]:
df['Last Name'] = ['Stuab', 'Arora', 'Conway']
df = df[['First Name', 'Last Name', 'Grade']] # reorder columns
df

  First Name Last Name  Grade
0       John     Stuab     85
1      Holly     Arora     90
2       Nina    Conway     95

### Exercise 6

In [12]:
dataset = {'First Name': ['Shweta', 'Leon', 'Shantanu', 'Linh'],
           'Last Name': ['Shetty', 'Lai', 'Mkherjee', 'Hoang']}

df = pd.DataFrame(dataset)
df

  First Name Last Name
0     Shweta    Shetty
1       Leon       Lai
2   Shantanu  Mkherjee
3       Linh     Hoang

### Exercise 7

In [13]:
dataset = {'Market': ['S&P 500', 'Dow', 'Nikkei'],
           'Last': [2932.05, 26485.01, 21087.16] }

df = pd.DataFrame(dataset)
change = [-21.51, -98.41, -453.81]

df['Change'] = change

percent_change = [-0.73, -0.37, -2.19]
df['Percentage Change'] = percent_change
df

    Market      Last  Change  Percentage Change
0  S&P 500   2932.05  -21.51              -0.73
1      Dow  26485.01  -98.41              -0.37
2   Nikkei  21087.16 -453.81              -2.19

### Looping through DataFrame

In [14]:
dataSet = {'Market': ['S&P 500', 'Dow', 'Nikkei'],
           'Last': [2932.05, 26485.01, 21087.16] }

df = pd.DataFrame(dataset)
df

    Market      Last
0  S&P 500   2932.05
1      Dow  26485.01
2   Nikkei  21087.16

In [15]:
for i in df:
    print(df[i])

0    S&P 500
1        Dow
2     Nikkei
Name: Market, dtype: object
0     2932.05
1    26485.01
2    21087.16
Name: Last, dtype: float64

In [47]:
for i in range(len(df)):
    print(df.iloc[i, 0])

35
22
35
23
23
26
25
32
41
22
25
24
20
19
32
30
19
20
18
28
20
19
24
20
25
18
19
28
28
34
30
33
27
30
27
21
29
29
23
41
18
37
20
26
17
40
20
20
29
29
22
32
24
22
20
19
16
24
33
26
17
21
36
30
30
20
22
22
28
21
21
31
21
15
31
18
27
19
22
20
24
22
16
18
20
31
24
23
21
36
15
20
24
33
37
15
28
19
36
37
42
34
33
23
22
21
22
24
38
26
22
23
31
27
30
40
27
19
35
29
30
23
33
20
29
31
21
25
31
27
41
22
20
25
34
30
33
23
26
38
35
27
30
39
36
27
27
24
32
24
23
25
21
37
29
36
27
37
26
21
14
32
25
31
17
29
23
24
19
29
23
35
20
26
32
24
33
18
37
19
34
26
20
36
27
33
40
21
28
26
24
36
22
27
33
25
34
36
23
34

In [17]:
for i in range(len(df)):
    print(df.loc[i]['Market'])

S&P 500
Dow
Nikkei

### Exercise 8

In [18]:
for i in range(len(df)):
    print(df.loc[i]['Last'])

2932.05
26485.01
21087.16

In [19]:
for i in range(len(df)):
    print(df.iloc[i, 1])

2932.05
26485.01
21087.16

In [20]:
df

    Market      Last
0  S&P 500   2932.05
1      Dow  26485.01
2   Nikkei  21087.16

In [21]:
df.values[0]

array(['S&P 500', 2932.05], dtype=object)

### Appending DataFrames

In [22]:
dataSet = {'Market': ['S&P 500', 'Dow', 'Nikkei'],
           'Last': [2932.05, 26485.01, 21087.16] }

df1 = pd.DataFrame(dataset)

dataset2 = { 'Market': ['Hang Seng', 'DAX'],
             'Last': [26918.58, 11872.44]}
df2 = pd.DataFrame(dataset2)
print(df2)

df1 = df1._append(df2)
df1

      Market      Last
0  Hang Seng  26918.58
1        DAX  11872.44

      Market      Last
0    S&P 500   2932.05
1        Dow  26485.01
2     Nikkei  21087.16
0  Hang Seng  26918.58
1        DAX  11872.44

In [23]:
dataset = {'Market': ['S&P 500', 'Dow', 'Nikkei'],
           'Last': [2932.05, 26485.01, 21087.16] }
df1 = pd.DataFrame(dataset)

dataset2 = { 'Market': ['Hang Seng', 'DAX'],
             'Last': [26918.58, 11872.44]}
df2 = pd.DataFrame(dataset2)

dataset3 = {'Market': ['FTSE100'],
            'Last': ['7,407.06']}
df3 = pd.DataFrame(dataset3)

df1 = df1._append(df2)._append(df3)
df1

      Market      Last
0    S&P 500   2932.05
1        Dow  26485.01
2     Nikkei  21087.16
0  Hang Seng  26918.58
1        DAX  11872.44
0    FTSE100  7,407.06

In [24]:
dataset = {'Market': ['S&P 500', 'Dow'],
           'Last': [2932.05, 26485.01 ]}
stock_dict = {'Market': 'Nikkei',
              'Last': 21087.16 }
df = pd.DataFrame(dataset)

df = df._append(stock_dict, ignore_index=True)
df

    Market      Last
0  S&P 500   2932.05
1      Dow  26485.01
2   Nikkei  21087.16

### Exercise 11

In [25]:
dataset = {'Market': ['S&P 500', 'Dow'],
           'Last': [2932.05, 26485.01 ]}
dax_dict = {'Market': 'DAX',
            'Last': 11872.44}

df = pd.DataFrame(dataset)
df = df._append(dax_dict, ignore_index=True)
df

    Market      Last
0  S&P 500   2932.05
1      Dow  26485.01
2      DAX  11872.44

### Example 12

In [26]:
import pandas as pd

path = r"C:\Users\linho\Desktop\CST\term3\pred_analytics\data\babysamp-98.txt"

df = pd.read_table(path, sep='\t')

# show all columns
pd.set_option('display.max_columns', None)

# Increase number of columns that display on one line
pd.set_option('display.width', 1000)

print('\nFIRST and BOTTOM TWO ROWS')
print(df.head(2))
print(df.tail(2))

print('\nDATA TYPES')
print(df.dtypes)

print('\nSTATISTIC SUMMARIES for NUMERIC COLUMNS')
print(df.describe())

print('\nSTATISTIC SUMMARIES for DATE and STRING COLUMNS')
print(df.describe(include=['object']))

FIRST and BOTTOM TWO ROWS
   MomAge  DadAge  MomEduc  MomMarital  numlive  dobmm  gestation sex  weight  prenatalstart  orig.id  preemie
0      35    35.0     17.0           1        2      2         39   F    3175            1.0  1047483    False
1      22    21.0     12.0           1        1      3         42   F    3884            2.0  1468100    False
     MomAge  DadAge  MomEduc  MomMarital  numlive  dobmm  gestation sex  weight  prenatalstart  orig.id  preemie
198      23    26.0     11.0           1        1      8         39   M    3572            2.0  1254365    False
199      34    35.0     12.0           1        3      9         36   M    2552            2.0  3088344     True

DATA TYPES
MomAge             int64
DadAge           float64
MomEduc          float64
MomMarital         int64
numlive            int64
dobmm              int64
gestation          int64
sex               object
weight             int64
prenatalstart    float64
orig.id            int64
preemie             bool
dtype: object

STATISTIC SUMMARIES for NUMERIC COLUMNS
           MomAge      DadAge     MomEduc  MomMarital    numlive       dobmm   gestation       weight  prenatalstart       orig.id
count  200.000000  166.000000  188.000000  200.000000  200.00000  200.000000  200.000000   200.000000     195.000000  2.000000e+02
mean    26.585000   30.060241   12.808511    1.385000    0.92000    6.540000   38.925000  3282.695000       2.400000  2.042214e+06
std      6.484057    6.877895    2.785665    0.487816    1.09984    3.458062    2.581218   568.702033       1.493629  1.061349e+06
min     14.000000   18.000000    2.000000    1.000000    0.00000    1.000000   23.000000   907.000000       0.000000  5.159300e+04
25%     21.000000   24.000000   12.000000    1.000000    0.00000    3.000000   38.000000  2934.750000       2.000000  1.158653e+06
50%     26.000000   29.500000   12.000000    1.000000    1.00000    7.000000   39.000000  3325.000000       2.000000  1.994176e+06
75%     31.250000   35.000000   15.000000    2.000000    1.00000    9.250000   40.000000  3629.000000       3.000000  2.929115e+06
max     42.000000   48.000000   17.000000    2.000000    5.00000   12.000000   47.000000  4825.000000       9.000000  3.916227e+06

STATISTIC SUMMARIES for DATE and STRING COLUMNS
        sex
count   200
unique    2
top       M
freq    103

### Exercise 12

In [27]:
path = r"C:\Users\linho\Desktop\CST\term3\pred_analytics\data\bodyfat.txt"

df = pd.read_table(path, sep='\t')
df

     Density  Pct.BF  Age  Weight  Height  Neck  Chest  Abdomen      Waist    Hip  Thigh  Knee  Ankle  Bicep  Forearm  Wrist
0     1.0708    12.3   23  154.25   67.75  36.2   93.1     85.2  33.543307   94.5   59.0  37.3   21.9   32.0     27.4   17.1
1     1.0853     6.1   22  173.25   72.25  38.5   93.6     83.0  32.677165   98.7   58.7  37.3   23.4   30.5     28.9   18.2
2     1.0414    25.3   22  154.00   66.25  34.0   95.8     87.9  34.606299   99.2   59.6  38.9   24.0   28.8     25.2   16.6
3     1.0751    10.4   26  184.75   72.25  37.4  101.8     86.4  34.015748  101.2   60.1  37.3   22.8   32.4     29.4   18.2
4     1.0340    28.7   24  184.25   71.25  34.4   97.3    100.0  39.370079  101.9   63.2  42.2   24.0   32.2     27.7   17.7
..       ...     ...  ...     ...     ...   ...    ...      ...        ...    ...    ...   ...    ...    ...      ...    ...
245   1.0736    11.0   70  134.25   67.00  34.9   89.2     83.6  32.913386   88.8   49.6  34.8   21.5   25.6     25.7   18.5
246   1.0236    33.6   72  201.00   69.75  40.9  108.5    105.0  41.338583  104.5   59.6  40.8   23.2   35.2     28.6   20.1
247   1.0328    29.3   72  186.75   66.00  38.9  111.1    111.5  43.897638  101.7   60.3  37.3   21.5   31.3     27.2   18.0
248   1.0399    26.0   72  190.75   70.50  38.9  108.3    101.3  39.881890   97.8   56.0  41.6   22.7   30.5     29.4   19.8
249   1.0271    31.9   74  207.50   70.00  40.8  112.4    108.5  42.716535  107.1   59.3  42.2   24.6   33.7     30.0   20.9

[250 rows x 16 columns]

In [28]:
df.head(2)

   Density  Pct.BF  Age  Weight  Height  Neck  Chest  Abdomen      Waist   Hip  Thigh  Knee  Ankle  Bicep  Forearm  Wrist
0   1.0708    12.3   23  154.25   67.75  36.2   93.1     85.2  33.543307  94.5   59.0  37.3   21.9   32.0     27.4   17.1
1   1.0853     6.1   22  173.25   72.25  38.5   93.6     83.0  32.677165  98.7   58.7  37.3   23.4   30.5     28.9   18.2

In [29]:
df.tail(2)

     Density  Pct.BF  Age  Weight  Height  Neck  Chest  Abdomen      Waist    Hip  Thigh  Knee  Ankle  Bicep  Forearm  Wrist
248   1.0399    26.0   72  190.75    70.5  38.9  108.3    101.3  39.881890   97.8   56.0  41.6   22.7   30.5     29.4   19.8
249   1.0271    31.9   74  207.50    70.0  40.8  112.4    108.5  42.716535  107.1   59.3  42.2   24.6   33.7     30.0   20.9

In [30]:
df.describe().round(2)

       Density  Pct.BF     Age  Weight  Height    Neck   Chest  Abdomen   Waist     Hip   Thigh    Knee   Ankle   Bicep  Forearm   Wrist
count   250.00  250.00  250.00  250.00  250.00  250.00  250.00   250.00  250.00  250.00  250.00  250.00  250.00  250.00   250.00  250.00
mean      1.06   19.03   44.88  178.08   70.30   37.94  100.66    92.29   36.33   99.65   59.25   38.53   23.07   32.22    28.66   18.22
std       0.02    8.29   12.65   27.04    2.62    2.29    8.15    10.21    4.02    6.44    4.91    2.31    1.65    2.92     2.03    0.91
min       1.00    0.00   22.00  118.50   64.00   31.10   79.30    69.40   27.32   85.00   47.20   33.00   19.10   24.80    21.00   15.80
25%       1.04   12.42   35.25  158.50   68.25   36.40   94.25    84.52   33.28   95.50   56.00   36.92   22.00   30.20    27.30   17.60
50%       1.05   19.20   43.00  176.12   70.00   38.00   99.60    90.90   35.79   99.30   58.95   38.45   22.80   32.00    28.70   18.30
75%       1.07   25.20   54.00  196.75   72.25   39.40  105.30    99.18   39.05  103.18   62.25   39.88   24.00   34.30    30.00   18.80
max       1.11   47.50   81.00  262.75   77.75   43.90  128.30   126.20   49.69  125.60   74.40   46.00   33.90   39.10    34.90   21.40

In [31]:
df.dtypes

Density    float64
Pct.BF     float64
Age          int64
Weight     float64
Height     float64
Neck       float64
Chest      float64
Abdomen    float64
Waist      float64
Hip        float64
Thigh      float64
Knee       float64
Ankle      float64
Bicep      float64
Forearm    float64
Wrist      float64
dtype: object

### Extracting Column Subset

In [32]:
dataset = {'Market': ['S&P 500', 'Dow', 'Nikkei'],
           'Last': [2932.05, 26485.01, 21087.16] }

df = pd.DataFrame(dataset)

change = [-21.51, -98.41, -453.83]

df['Change'] = change

df2 = df[['Market', 'Change']]
df2

    Market  Change
0  S&P 500  -21.51
1      Dow  -98.41
2   Nikkei -453.83

### Exercise 13

In [33]:
path = r"C:\Users\linho\Desktop\CST\term3\pred_analytics\data\bodyfat.txt"

df = pd.read_table(path, sep='\t')

df1 = df[['Height', 'Waist', 'Weight', 'Pct.BF']]
df1

     Height      Waist  Weight  Pct.BF
0     67.75  33.543307  154.25    12.3
1     72.25  32.677165  173.25     6.1
2     66.25  34.606299  154.00    25.3
3     72.25  34.015748  184.75    10.4
4     71.25  39.370079  184.25    28.7
..      ...        ...     ...     ...
245   67.00  32.913386  134.25    11.0
246   69.75  41.338583  201.00    33.6
247   66.00  43.897638  186.75    29.3
248   70.50  39.881890  190.75    26.0
249   70.00  42.716535  207.50    31.9

[250 rows x 4 columns]

In [34]:
df1.head(1)

   Height      Waist  Weight  Pct.BF
0   67.75  33.543307  154.25    12.3

### example 14: Changing column names

In [35]:
path = r"C:\Users\linho\Desktop\CST\term3\pred_analytics\data\babysamp-98.txt"

df = pd.read_table(path, sep='\t')

df = df.rename({'MomAge': 'Mom Age',
                'DadAge': 'Dad Age',
                'MomEduc': 'Mom Edu',
                'weight': 'Weight'},
               axis=1)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)
df.head()

   Mom Age  Dad Age  Mom Edu  MomMarital  numlive  dobmm  gestation sex  Weight  prenatalstart  orig.id  preemie
0       35     35.0     17.0           1        2      2         39   F    3175            1.0  1047483    False
1       22     21.0     12.0           1        1      3         42   F    3884            2.0  1468100    False
2       35     42.0     15.0           1        0      6         39   F    3030            2.0  2260016    False
3       23      NaN      6.0           1        2      8         40   F    3629            1.0  3583052    False
4       23     28.0     13.0           1        0      9         42   F    3481            2.0   795674    False

In [36]:
path = r"C:\Users\linho\Desktop\CST\term3\pred_analytics\data\bodyfat.txt"

df = pd.read_table(path, sep='\t')

df1 = df[['Height', 'Waist', 'Weight', 'Pct.BF']]
df1 = df1.rename({'Pct.BF': 'Percent Body Fat'},
                 axis=1)
df1

     Height      Waist  Weight  Percent Body Fat
0     67.75  33.543307  154.25              12.3
1     72.25  32.677165  173.25               6.1
2     66.25  34.606299  154.00              25.3
3     72.25  34.015748  184.75              10.4
4     71.25  39.370079  184.25              28.7
..      ...        ...     ...               ...
245   67.00  32.913386  134.25              11.0
246   69.75  41.338583  201.00              33.6
247   66.00  43.897638  186.75              29.3
248   70.50  39.881890  190.75              26.0
249   70.00  42.716535  207.50              31.9

[250 rows x 4 columns]

### Analyzing frequencies

In [37]:
path = r"C:\Users\linho\Desktop\CST\term3\pred_analytics\data\babysamp-98.txt"

df = pd.read_table(path, sep='\t')

df = df.rename({'MomAge': 'Mom Age',
                'DadAge': 'Dad Age',
                'MomEduc': 'Mom Edu',
                'weight': 'Weight'},
               axis=1)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)
df.head()

   Mom Age  Dad Age  Mom Edu  MomMarital  numlive  dobmm  gestation sex  Weight  prenatalstart  orig.id  preemie
0       35     35.0     17.0           1        2      2         39   F    3175            1.0  1047483    False
1       22     21.0     12.0           1        1      3         42   F    3884            2.0  1468100    False
2       35     42.0     15.0           1        0      6         39   F    3030            2.0  2260016    False
3       23      NaN      6.0           1        2      8         40   F    3629            1.0  3583052    False
4       23     28.0     13.0           1        0      9         42   F    3481            2.0   795674    False

In [38]:
print('\nTOP FREQUENCY FIRST')
print(df['Mom Age'].value_counts())

TOP FREQUENCY FIRST
Mom Age
20    16
24    13
22    13
23    12
27    12
21    11
19    10
26     9
30     9
29     9
33     9
25     8
36     8
31     7
18     6
32     6
28     6
34     6
37     6
35     5
41     3
40     3
17     3
15     3
16     2
38     2
42     1
39     1
14     1
Name: count, dtype: int64

In [39]:
print('LOWEST FREQUENCY FIRST')
df['Mom Age'].value_counts(ascending=True)

LOWEST FREQUENCY FIRST

Mom Age
14     1
42     1
39     1
16     2
38     2
41     3
17     3
40     3
15     3
35     5
32     6
18     6
28     6
34     6
37     6
31     7
36     8
25     8
26     9
29     9
30     9
33     9
19    10
21    11
23    12
27    12
22    13
24    13
20    16
Name: count, dtype: int64

In [40]:
df['Mom Age'].value_counts().sort_index()

Mom Age
14     1
15     3
16     2
17     3
18     6
19    10
20    16
21    11
22    13
23    12
24    13
25     8
26     9
27    12
28     6
29     9
30     9
31     7
32     6
33     9
34     6
35     5
36     8
37     6
38     2
39     1
40     3
41     3
42     1
Name: count, dtype: int64

In [41]:
path = r"C:\Users\linho\Desktop\CST\term3\pred_analytics\data\babysamp-98.txt"

df = pd.read_table(path, sep='\t')

df = df.rename({'MomAge': 'Mom Age',
                'DadAge': 'Dad Age',
                'MomEduc': 'Mom Edu',
                'weight': 'Weight'},
               axis=1)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

df['Mom Edu'].value_counts().sort_index()

Mom Edu
2.0      1
3.0      1
5.0      2
6.0      4
7.0      2
8.0      6
10.0     8
11.0    13
12.0    58
13.0    16
14.0    27
15.0     9
16.0    30
17.0    11
Name: count, dtype: int64

In [42]:
df_sorted = df.sort_values(['Mom Age', 'Weight'],
                           ascending=[False, True])
df_sorted

     Mom Age  Dad Age  Mom Edu  MomMarital  numlive  dobmm  gestation sex  Weight  prenatalstart  orig.id  preemie
100       42     43.0     15.0           1        4      4         40   M    4224            2.0  2582947    False
39        41     47.0     12.0           1        3      7         38   M    2182            2.0  1622541    False
8         41     39.0     14.0           1        0     11         36   M    2834            2.0  2481971     True
130       41     41.0     16.0           1        2      7         40   F    4000            1.0  2267907    False
115       40     32.0     17.0           1        1     10         36   M    2268            1.0    51593     True
..       ...      ...      ...         ...      ...    ...        ...  ..     ...            ...      ...      ...
56        16      NaN      8.0           2        0      7         39   M    1985            2.0  1247735    False
95        15      NaN      8.0           2        0      2         36   F    2552            5.0  3145461     True
90        15      NaN      8.0           2        0      7         38   F    2892            1.0   945363    False
73        15     20.0      NaN           2        0      5         44   F    3459            5.0  1316782    False
160       14      NaN      8.0           2        0     10         38   F    2977            6.0  1123508    False

[200 rows x 12 columns]

### Exercise 16

In [43]:
path = r"C:\Users\linho\Desktop\CST\term3\pred_analytics\data\babysamp-98.txt"

df = pd.read_table(path, sep='\t')
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

df = df.rename({'MomAge': 'Mom Age',
                'DadAge': 'Dad Age',
                'MomEduc': 'Mom Edu',
                'gestation': 'Gestation',
                'weight': 'Weight'},
               axis=1)

df_sorted = df.sort_values(['Gestation', 'Weight'],
                           ascending=[True, True])
df_sorted

     Mom Age  Dad Age  Mom Edu  MomMarital  numlive  dobmm  Gestation sex  Weight  prenatalstart  orig.id  preemie
82        16      NaN      NaN           2        0     11         23   F    1049            2.0  1578022     True
93        33     31.0      NaN           1        1      7         27   F     907            2.0  3456969     True
38        23      NaN      NaN           2        2     11         33   M    1671            1.0  2855152     True
14        32     38.0     12.0           1        0      4         33   M    1729            2.0  3037162     True
83        18     18.0      NaN           2        1     11         33   F    2560            2.0  1283550     True
..       ...      ...      ...         ...      ...    ...        ...  ..     ...            ...      ...      ...
73        15     20.0      NaN           2        0      5         44   F    3459            5.0  1316782    False
117       19      NaN     13.0           2        0      6         44   F    3840            4.0   407070    False
96        28     37.0     11.0           2        1     10         44   F    4337            3.0  1796102    False
190       24     23.0     11.0           1        1      7         45   F    3200            3.0  2807831    False
48        29     35.0     10.0           1        5      2         47   M    3345            0.0  2889084    False

[200 rows x 12 columns]

### Filtering

In [44]:
df_filtered = df[(df['Dad Age'] >= 40) & (df['Mom Age'] >= 40)]
df_filtered

     Mom Age  Dad Age  Mom Edu  MomMarital  numlive  dobmm  Gestation sex  Weight  prenatalstart  orig.id  preemie
39        41     47.0     12.0           1        3      7         38   M    2182            2.0  1622541    False
100       42     43.0     15.0           1        4      4         40   M    4224            2.0  2582947    False
130       41     41.0     16.0           1        2      7         40   F    4000            1.0  2267907    False
186       40     44.0     12.0           1        1      3         36   M    2693            2.0  2990722     True

### Exercise 17

In [45]:
print(f'Count: {df['Mom Age'].count()}')
print(f'Min: {df['Mom Age'].min()}')
print(f'Max: {df['Mom Age'].max()}')
print(f'Mean: {df['Mom Age'].mean()}')
print(f'Median: {df['Mom Age'].median()}')
print(f'Standard Deviation: {df['Mom Age'].std()}')

Count: 200
Min: 14
Max: 42
Mean: 26.585
Median: 26.0
Standard Deviation: 6.484056596741637

## Grouping

In [48]:
path = r"C:\Users\linho\Desktop\CST\term3\pred_analytics\data\phone_data.csv"

df = pd.read_csv(path)
df.head()

   index            date  duration  item    month   network network_type
0      0  15/10/14 06:58    34.429  data  2014-11      data         data
1      1  15/10/14 06:58    13.000  call  2014-11  Vodafone       mobile
2      2  15/10/14 14:46    23.000  call  2014-11    Meteor       mobile
3      3  15/10/14 14:48     4.000  call  2014-11     Tesco       mobile
4      4  15/10/14 17:27     4.000  call  2014-11     Tesco       mobile

In [67]:
# summarize call counts by phone network
call_counts = df.groupby('network')['index'].count()
call_counts

network
Meteor        87
Tesco         84
Three        215
Vodafone     215
data         150
landline      42
special        3
voicemail     27
world          7
Name: index, dtype: int64

In [68]:
type(call_counts)

pandas.core.series.Series

In [72]:
# convert a Series to a DataFrame
series_to_df = df.groupby('network')['index'].count().reset_index(name='# Call')
series_to_df

     network  # Call
0     Meteor      87
1      Tesco      84
2      Three     215
3   Vodafone     215
4       data     150
5   landline      42
6    special       3
7  voicemail      27
8      world       7

In [61]:
type(df_reverse)

pandas.core.frame.DataFrame

In [70]:
dfStats = df.groupby('network')['index']\
  .count().reset_index().rename(columns={'index': '# Calls'})
dfStats

     network  # Calls
0     Meteor       87
1      Tesco       84
2      Three      215
3   Vodafone      215
4       data      150
5   landline       42
6    special        3
7  voicemail       27
8      world        7

In [91]:
path = r"C:\Users\linho\Desktop\CST\term3\pred_analytics\data\phone_data.csv"

phone_data_df = pd.read_csv(path)

df_stats = phone_data_df.groupby('network')['index'].count().reset_index(name='# Call')

df_duration_mean = df.groupby('network')['duration'].mean().reset_index(name='Duration Mean')

df_duration_max = df.groupby('network')['duration'].max().reset_index(name='Duration Max')

df_stats['Duration Mean'] = df_duration_mean['Duration Mean']
df_stats['Duration Max'] = df_duration_max['Duration Max']

df_duration_min = df.groupby('network')['duration'].min().reset_index(name='Duration Min')
df_duration_std = df.groupby('network')['duration'].std().reset_index(name='Duration Std.')

df_stats['Duration Min'] = df_duration_min['Duration Min']
df_stats['Duration Std.'] = df_duration_std['Duration Std.']
df_stats

     network  # Call  Duration Mean  Duration Max  Duration Min  Duration Std.
0     Meteor      87      83.137931      1090.000         1.000     169.690291
1      Tesco      84     164.773810      1234.000         1.000     227.471611
2      Three     215     170.004651      2328.000         1.000     368.311638
3   Vodafone     215      68.697674      1859.000         1.000     232.527090
4       data     150      34.429000        34.429        34.429       0.000000
5   landline      42     438.880952     10528.000         3.000    1631.415609
6    special       3       1.000000         1.000         1.000       0.000000
7  voicemail      27      65.740741       174.000         1.000      44.294984
8      world       7       1.000000         1.000         1.000       0.000000

In [97]:
### A more efficient way to aggregate the column data
df_stats_eff = phone_data_df.groupby('network').agg(
    **{
        '# Call': ('index', 'count'),
        'Min': ('duration', 'min'),
        'Max': ('duration', 'max'),
        'Mean': ('duration', 'mean'),
        'Std.': ('duration', 'std'),
    }
).reset_index()
df_stats_eff

     network  # Call     Min        Max        Mean         Std.
0     Meteor      87   1.000   1090.000   83.137931   169.690291
1      Tesco      84   1.000   1234.000  164.773810   227.471611
2      Three     215   1.000   2328.000  170.004651   368.311638
3   Vodafone     215   1.000   1859.000   68.697674   232.527090
4       data     150  34.429     34.429   34.429000     0.000000
5   landline      42   3.000  10528.000  438.880952  1631.415609
6    special       3   1.000      1.000    1.000000     0.000000
7  voicemail      27   1.000    174.000   65.740741    44.294984
8      world       7   1.000      1.000    1.000000     0.000000

In [95]:
import pandas as pd, numpy as np, time

N = 1_000_000
df = pd.DataFrame({
    "network": np.random.choice(["AT&T","Verizon","T-Mobile"], size=N),
    "index": np.arange(N),
    "duration": np.random.randint(1, 1000, size=N)
})

# Original approach
start = time.time()
count = df.groupby("network")["index"].count()
mean = df.groupby("network")["duration"].mean()
max_ = df.groupby("network")["duration"].max()
min_ = df.groupby("network")["duration"].min()
std = df.groupby("network")["duration"].std()
end = time.time()
print("Separate groupbys:", end - start)

# Aggregated approach
start = time.time()
stats = df.groupby("network").agg(
    **{
        "# Call": ("index", "count"),
        "Duration Mean": ("duration", "mean"),
        "Duration Max": ("duration", "max"),
        "Duration Min": ("duration", "min"),
        "Duration Std.": ("duration", "std"),
    }
)
end = time.time()
print("Single agg:", end - start)

Separate groupbys: 0.7601945400238037
Single agg: 0.17676138877868652

### Exercise 19

In [107]:
dir = r"C:\Users\linho\Desktop\CST\term3\pred_analytics\data"
file = r'\phone_data.csv'

phone_data_df = pd.read_csv(dir + file, encoding='utf-8')

df_stats = phone_data_df.groupby('network_type')['index'].count().reset_index(name='Total Calls')
df_duration_mean = phone_data_df.groupby('network_type')['duration'].mean().reset_index(name='Duration Mean')
df_duration_max = phone_data_df.groupby('network_type')['duration'].max().reset_index(name='Duration Max')
df_duration_std = phone_data_df.groupby('network_type')['duration'].std().reset_index(name='Duration Std.')

df_stats['Duration Mean'] = df_duration_mean['Duration Mean']
df_stats['Duration Max'] = df_duration_max['Duration Max']
df_stats['Duration Std.'] = df_duration_std['Duration Std.']
df_stats

  network_type  Total Calls  Duration Mean  Duration Max  Duration Std.
0         data          150      34.429000        34.429       0.000000
1     landline           42     438.880952     10528.000    1631.415609
2       mobile          601     120.457571      2328.000     285.077689
3      special            3       1.000000         1.000       0.000000
4    voicemail           27      65.740741       174.000      44.294984
5        world            7       1.000000         1.000       0.000000

In [108]:
df_stat_agg = phone_data_df.groupby('network_type').agg(
    **{
        'Total Calls': ('index', 'count'),
        'Mean': ('duration', 'mean'),
        'Max': ('duration', 'max'),
        'Std.': ('duration', 'std')
    }
).reset_index()
df_stat_agg

  network_type  Total Calls        Mean        Max         Std.
0         data          150   34.429000     34.429     0.000000
1     landline           42  438.880952  10528.000  1631.415609
2       mobile          601  120.457571   2328.000   285.077689
3      special            3    1.000000      1.000     0.000000
4    voicemail           27   65.740741    174.000    44.294984
5        world            7    1.000000      1.000     0.000000

In [121]:
file = r'\babysamp-98.txt'

babysamp_df = pd.read_table(dir + file, sep='\t')

df_stats = babysamp_df.groupby('sex').agg(
    **{
        'Max Weight': ('weight', 'max'),
        'Min Weight': ('weight', 'min'),
        'Mean Weight': ('weight', 'mean')
    }
).reset_index()
df_stats

  sex  Max Weight  Min Weight  Mean Weight
0   F        4825         907  3264.690722
1   M        4593        1671  3299.650485

In [114]:
babysamp_df

     MomAge  DadAge  MomEduc  MomMarital  numlive  dobmm  gestation sex  weight  prenatalstart  orig.id  preemie
0        35    35.0     17.0           1        2      2         39   F    3175            1.0  1047483    False
1        22    21.0     12.0           1        1      3         42   F    3884            2.0  1468100    False
2        35    42.0     15.0           1        0      6         39   F    3030            2.0  2260016    False
3        23     NaN      6.0           1        2      8         40   F    3629            1.0  3583052    False
4        23    28.0     13.0           1        0      9         42   F    3481            2.0   795674    False
..      ...     ...      ...         ...      ...    ...        ...  ..     ...            ...      ...      ...
195      25     NaN     12.0           2        2      5         40   F    2858            2.0  2329810    False
196      34    35.0     11.0           1        1      6         40   M    2530            2.0   435373    False
197      36    37.0     16.0           1        0      2         37   M    3204            1.0  3315797    False
198      23    26.0     11.0           1        1      8         39   M    3572            2.0  1254365    False
199      34    35.0     12.0           1        3      9         36   M    2552            2.0  3088344     True

[200 rows x 12 columns]

In [125]:
female_df = babysamp_df[babysamp_df['sex'] == 'F']
female_df.groupby('sex').agg(
    **{
        'Max Weight': ('weight', 'max'),
        'Min Weight': ('weight', 'min'),
        'Mean Weight': ('weight', 'mean')
    }
).reset_index()

  sex  Max Weight  Min Weight  Mean Weight
0   F        4825         907  3264.690722

## Generating a Calculated Column

In [127]:
dataset = {'Fahrenheit': [85, 95, 91]}

df = pd.DataFrame(dataset)

df['Celsius'] =(df['Fahrenheit'] - 32) * 5 / 9
df

   Fahrenheit    Celsius
0          85  29.444444
1          95  35.000000
2          91  32.777778

### Exercise 21

In [128]:
df['Kelvin'] = df['Celsius'] + 273.15
df

   Fahrenheit    Celsius      Kelvin
0          85  29.444444  302.594444
1          95  35.000000  308.150000
2          91  32.777778  305.927778

## Grouping on multiple columns

In [135]:
df2 = phone_data_df.groupby(['network', 'item'])['duration'].mean().reset_index()

In [136]:
df2

      network  item    duration
0      Meteor  call  133.333333
1      Meteor   sms    1.000000
2       Tesco  call  194.760563
3       Tesco   sms    1.000000
4       Three  call  284.875000
5       Three   sms    1.000000
6    Vodafone  call  221.530303
7    Vodafone   sms    1.000000
8        data  data   34.429000
9    landline  call  438.880952
10    special   sms    1.000000
11  voicemail  call   65.740741
12      world   sms    1.000000

In [141]:
dir = r'C:\Users\linho\Desktop\CST\term3\pred_analytics\data'
file = r'\phone_data.csv'

phone_data = pd.read_csv(dir + file, encoding='utf-8')

df_grouped = phone_data.groupby(['network_type', 'item'])['index'].count().reset_index()
df_grouped

  network_type  item  index
0         data  data    150
1     landline  call     42
2       mobile  call    319
3       mobile   sms    282
4      special   sms      3
5    voicemail  call     27
6        world   sms      7